# Generated by Django 2.1 on 2018-08-07 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_level', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Municipio')),
                ('address', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
